[project]
name = "bookly"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.117.1",
]

[tool.ruff.lint]
select = ["E", "F", "UP", "B", "SIM", "I", "FAST"]
